
group 'jio.coresdk.coresdk_plugin'
version '0.0.24'

buildscript {
    ext {
        kotlin_version = '2.0.0'
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

def properties = new Properties()
def rootPropertiesFile = file("${rootDir}/../credentials.properties")

if (rootPropertiesFile.exists()) {
    rootPropertiesFile.withInputStream { stream ->
    properties.load(stream)
  }
}

def githubUsername = properties['username'] ?: ''
def githubPassword = properties['password'] ?: ''

if (!githubUsername || !githubPassword) {
  throw new GradleException("GitHub credentials not found. Please ensure `credentials.properties` exists at the project root.")
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        // Enables Jetpack Compose for this module
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion "1.4.8"
    }

    kotlinOptions {
        jvmTarget = '11'
    }



    defaultConfig {
        minSdkVersion 21
    }

}
rootProject.allprojects {
    repositories {
        maven {
            credentials {
                username githubUsername
                password githubPassword
            }
            url = uri("https://maven.pkg.github.com/JioMeet/JioMeetCoreTemplateSDK_ANDROID")
        }
        google()
        mavenCentral()
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10"
    implementation 'com.jiomeet.platform:jiomeetcoretemplatesdk:4.3.1-SNAPSHOT-2'
}
